#!/usr/bin/env python3
"""Static fail-closed review for the desktop product and accessibility boundary."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import NoReturn


ROOT = Path(__file__).resolve().parents[2]


def fail(message: str) -> NoReturn:
    raise SystemExit(f"desktop product check failed: {message}")


def text(path: str) -> str:
    target = ROOT / path
    if not target.is_file():
        fail(f"missing {path}")
    return target.read_text(encoding="utf-8")


def require(content: str, markers: tuple[str, ...], label: str) -> None:
    missing = [marker for marker in markers if marker not in content]
    if missing:
        fail(f"{label} is missing {missing}")


def reject(content: str, markers: tuple[str, ...], label: str) -> None:
    present = [marker for marker in markers if marker in content]
    if present:
        fail(f"{label} contains stale claims {present}")


def digest(path: str) -> str:
    return hashlib.sha256((ROOT / path).read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence", type=Path)
    args = parser.parse_args()

    ipc = text("apps/desktop/src/ipc.rs")
    runtime = text("apps/desktop/src/runtime.rs")
    native = text("apps/desktop/src/main.rs")
    desktop_manifest = text("apps/desktop/Cargo.toml")
    native_contract = text("apps/desktop/src/native_backend.rs")
    macos_backend = text("apps/desktop/src/macos_native_backend.rs")
    macos_av_worker = text("apps/desktop/src/macos_native_backend/av_worker.rs")
    macos_normalized_worker = text(
        "apps/desktop/src/macos_native_backend/normalized_worker.rs"
    )
    windows_backend = text("apps/desktop/src/windows_native_backend.rs")
    rooted_io = text("apps/desktop/src/rooted_io.rs")
    gstreamer_bootstrap = text("apps/desktop/src/gstreamer_bootstrap.rs")
    macos_capture = text("crates/macos-screen-capture/src/lib.rs") + text(
        "crates/macos-screen-capture/src/platform.rs"
    )
    macos_normalized_capture = text(
        "crates/macos-screen-capture/src/normalized.rs"
    )
    windows_normalized_capture = text(
        "crates/windows-screen-capture/src/normalized.rs"
    )
    screen_capture = text("crates/media/src/screen_capture.rs")
    screen_pump = text("crates/media/src/screen_recording/pump.rs")
    screen_recording = text("crates/media/src/screen_recording.rs")
    ui = text("apps/desktop/ui/src/main.rs")
    region_picker = text("apps/desktop/ui/src/browser/region_picker.rs")
    css = text("crates/ui/styles/tailwind.css")
    ui_components = "".join(
        text(path)
        for path in (
            "crates/ui/src/button.rs",
            "crates/ui/src/display.rs",
            "crates/ui/src/form.rs",
            "crates/ui/src/layout.rs",
        )
    )
    capability = json.loads(text("apps/desktop/capabilities/main.json"))
    permissions = text("apps/desktop/permissions/desktop.toml")
    finalize_permission = text(
        "apps/desktop/permissions/autogenerated/finalize_instant.toml"
    )
    journey = text("apps/desktop/tests/fake_desktop_journey.rs")
    architecture = text("docs/architecture/desktop-product-v1.md")
    adr = text("docs/adr/0005-leptos-rendering-and-tauri-shell.md")
    screen_evidence = text("docs/evidence/screen-capture-local.md")
    studio_evidence = text("docs/evidence/studio-mode-local.md")
    evidence_doc = text("docs/evidence/desktop-editor-a11y-local.md")
    operations = text("docs/operations/desktop-recovery-and-release.md")
    hardware_workflow = text(".github/workflows/desktop-real-hardware.yml")
    hardware_validator = text("scripts/ci/desktop-real-hardware.py")
    desktop_shell_smoke = text("scripts/ci/desktop-shell-smoke.py")

    require(
        ipc,
        (
            "pub const IPC_PROTOCOL_VERSION",
            "pub struct RequestEnvelope",
            "pub enum WindowRole",
            "pub enum IpcCommand",
            "completed_order",
            "PathOutOfScope",
            "CommandOutOfScope",
            "SequenceGap",
            '"recorder_poll"',
        ),
        "typed IPC",
    )
    require(
        runtime,
        (
            "pub const DESKTOP_RUNTIME_VERSION",
            "DesktopAdapterKind::Unavailable",
            "DesktopAdapterKind::DeterministicFake",
            "DesktopAdapterKind::NativeMacOs",
            "DesktopAdapterKind::NativeWindows",
            "pub fn dispatch_json",
            "pub fn dispatch_native_json",
            "pub fn advance_fake",
            "pub fn simulate_fake_device_loss",
            "pub fn simulate_fake_restart",
            "pub fn preflight_instant_finalize",
            "pub fn disable_native_instant_finalize",
            "InstantUiProgressV1",
            "Native capture supports selected-target video with optional system audio only.",
            "ExportProfile::EditableWebm",
            "NativeRecordingStopOutcome::Sealed",
            "NativeRecordingCancelOutcome::Cancelled",
            "legacy_desktop_selectable: true",
        ),
        "native runtime",
    )
    require(
        native,
        (
            "fn bootstrap_desktop",
            "fn dispatch_main",
            "async fn finalize_instant",
            "decode_instant_finalize_command",
            "reconciled_result",
            "InstantFinalizeService::not_configured()",
            'app.emit("frame-desktop://event-v1"',
            'cfg!(debug_assertions)',
            'FRAME_DESKTOP_FAKE_PIPELINE',
            'cfg!(all(target_os = "macos", feature = "macos-native"))',
            "bootstrap_desktop_gstreamer()",
            "RecorderAdapterState::NativeMacOsDisplay",
            "RecorderAdapterState::NativeWindowsDisplayWindowRegion",
            "DesktopAdapterKind::NativeMacOs",
            "DesktopAdapterKind::Unavailable",
            "(DesktopAdapterKind::Unavailable, None)",
        ),
        "Tauri boundary",
    )
    require(
        desktop_manifest,
        (
            'tauri-app = ["dep:tauri"]',
            'macos-native = [',
            'windows-native = [',
            '"dep:frame-media"',
            '"dep:frame-macos-av-capture"',
            '"dep:frame-macos-screen-capture"',
        ),
        "desktop feature boundary",
    )
    require(
        native_contract,
        (
            "pub trait NativeDesktopBackend",
            "pub struct NativeRegionDefinitionRequest",
            "pub struct NativeRegionDefinitionOutcome",
            "fn prepare_capture",
            "fn enumerate_targets",
            "fn select_target",
            "fn define_region",
            "fn start_recording",
            "fn poll_recording_terminal_failure",
            "fn stop_recording",
            "fn cancel_recording",
            "fn export_editable_webm",
        ),
        "native desktop contract",
    )
    require(
        macos_backend,
        (
            "records one opaque display, window, or region target",
            "preflight_screen_recording_runtime()",
            "PermissionPreflight::PromptRequired => source.request_permission()",
            "fn enumerate_targets",
            "fn select_target",
            "fn define_region",
            "fn start_recording",
            "if !request.exclude_frame_windows",
            "CursorCaptureMode::EmbeddedInFrame",
            "ScreenWorkerStart::prepare(",
            "ScreenRecording::start_preopened",
            "create_new_file(&staging_relative)",
            "publish_file_if_identity(",
            "publish_file_to_root_if_identity(",
            "ensure_media_directories_visible()",
            "ensure_export_directories_visible()",
            "export_staging_directory",
            "verify_published_rooted_file(",
            "stop_and_drain_frames()",
            "source_sha256",
            "fn poll_recording_terminal_failure(",
            "fn export_editable_webm(",
            "artifact.token == request.artifact_token",
            "artifact.revision == request.artifact_revision",
            "MacOsSystemAudioSource",
            "ScreenAudioRecording::start_preopened(",
            "system_audio_included",
        ),
        "macOS target and system-audio backend",
    )
    require(
        macos_normalized_worker,
        (
            "platform-neutral screen-only production worker",
            "pub(crate) trait NativeScreenSource",
            "BoundScreenCaptureSource::new",
            "ScreenCaptureIngress::new",
            "negotiate_screen_capture",
            "ScreenRecordingPump::new",
            "S::protected_content_policy()",
            "ScreenSourceFailureCode::ContentUnavailable",
        ),
        "shared normalized production worker",
    )
    require(
        windows_backend,
        (
            "pub struct WindowsNativeDesktopBackend",
            "WindowsNormalizedScreenCaptureSource",
            "ScreenWorkerStart::<WindowsNormalizedScreenCaptureSource>::prepare",
            "ProtectedContentPolicy::RequirePlatformRedaction",
            "frame_windows_excluded",
            "create_private_file",
            "publish_file",
            "metadata_is_indirect",
            "fn poll_recording_terminal_failure",
            "fn export_editable_webm",
        ),
        "Windows native desktop composition",
    )
    require(
        windows_normalized_capture,
        (
            "pub struct WindowsNormalizedScreenCaptureSource",
            "impl ScreenCaptureSource for WindowsNormalizedScreenCaptureSource",
            "platform_protected_content_redaction: true",
            "fn poll_stopped_event",
        ),
        "Windows normalized capture source",
    )
    require(
        macos_av_worker,
        (
            "STARTUP_CALIBRATION_TIMEOUT",
            "calibrate_av_startup",
            "SharedClockNormalizer",
            "at most one item",
            "poll_audio_first = !poll_audio_first",
            "stop_and_drain_frames()",
            "stop_and_drain_chunks()",
            "all_av_teardown_confirmed(",
            "recording.end_of_stream()",
            "recording.finish(&CancellationToken::new())",
            "Do not fabricate PCM",
        ),
        "macOS A/V ownership worker",
    )
    require(
        rooted_io,
        (
            "pub struct DirectoryIdentity",
            "pub fn matches_visible_path",
            "pub fn publish_file_to_root_if_identity",
            "RenameFlags::NOREPLACE",
        ),
        "descriptor-rooted publication boundary",
    )
    require(
        gstreamer_bootstrap,
        (
            "desktop_runtime_launch_plan()?",
            "plan.apply_to(&mut command)",
            "command.exec()",
            ".spawn()",
        ),
        "trusted desktop GStreamer bootstrap",
    )
    require(
        macos_capture,
        (
            "pub struct MacOsScreenCaptureSource",
            "pub fn preflight_permission",
            "pub fn request_permission",
            "pub fn enumerate_displays",
            "SCShareableContent::get()",
            "with_excluding_applications",
            "select_current_application",
            "SCFrameStatus::Idle",
            "pub fn poll_frame",
            "pub fn stop_and_drain_frames",
        ),
        "ScreenCaptureKit source",
    )
    require(
        macos_normalized_capture,
        (
            "pub struct MacOsNormalizedScreenCaptureSource",
            "impl ScreenCaptureSource for MacOsNormalizedScreenCaptureSource",
            "fn poll_stopped_event",
            "ScreenTargetKind::Display",
            "ScreenTargetKind::Window",
            "ScreenTargetKind::Region",
            "content_unavailable_failures: true",
            "ScreenSourceFailureCode::ContentUnavailable",
        ),
        "normalized ScreenCaptureKit source",
    )
    require(
        screen_capture + screen_pump,
        (
            "fn poll_stopped_event",
            "const MAX_STOP_TAIL_FRAMES: u16 = 16",
            "ScreenPumpError::StopTailExceeded",
            "poll_owned_stopped_event",
        ),
        "normalized screen stop tail",
    )
    require(
        screen_recording,
        (
            "pub struct ScreenRecording",
            "pub fn preflight_screen_recording_runtime",
            "pub fn start_preopened",
            "pub fn push_frame",
            "pub fn finish",
            "pub fn export_screen_recording_webm",
            "fdsink name=screen_recording_sink",
            "MAX_SCREEN_RECORDING_DURATION_NS",
            "MAX_SCREEN_RECORDING_OUTPUT_BYTES",
            "MIN_SCREEN_RECORDING_FREE_BYTES",
        ),
        "owned GStreamer screen recorder",
    )

    expected_permissions = [
        "allow-bootstrap-main",
        "allow-bootstrap-desktop",
        "allow-dispatch-main",
        "allow-finalize-instant",
    ]
    if capability.get("windows") != ["main"]:
        fail("capability is not restricted to the main WebView")
    if capability.get("permissions") != expected_permissions:
        fail("capability command allowlist drifted")
    for command in ("bootstrap_desktop", "dispatch_main"):
        require(
            permissions,
            (f'commands.allow = ["{command}"]', f'commands.deny = ["{command}"]'),
            f"{command} permission",
        )
    require(
        finalize_permission,
        (
            'identifier = "allow-finalize-instant"',
            'commands.allow = ["finalize_instant"]',
            'identifier = "deny-finalize-instant"',
            'commands.deny = ["finalize_instant"]',
        ),
        "finalize_instant permission",
    )

    require(
        ui,
        (
            'class="skip-link"',
            '<UiStyles/>',
            '<NavigationMenu attr:aria-label="Desktop workspace">',
            '<main id="main-content"',
            'id="recorder"',
            'id="recovery"',
            'id="editor"',
            'id="settings"',
            'aria-label="Recording controls"',
            'aria-label="Live input meters"',
            'legend>"Numeric timeline alternative"',
            'attr:role="status" attr:aria-live="polite"',
            'attr:role="alertdialog" attr:aria-modal="true"',
            'aria-describedby="timeline-help"',
            'class="instant-sharing"',
            'class="instant-progress"',
            'instant_progress_announcement',
            'instant_error_message',
            "RecorderAdapterState::NativeMacOsDisplay",
            "RecorderAdapterState::NativeWindowsDisplayWindowRegion",
            "ExportProfile::EditableWebm",
            "Native macOS capture records the selected target and can optionally include system audio.",
            '<Progress',
            '<Meter',
        ),
        "Leptos accessibility surface",
    )
    require(
        region_picker,
        (
            "pub(super) fn RegionPicker",
            'legend>"Screen region"',
            'IpcCommand::CaptureRegionDefine',
            'attr:r#type="number"',
            'attr:min="0"',
        ),
        "bounded accessible region picker",
    )
    require(
        ui_components,
        (
            "pub fn Button(",
            "pub fn Input(",
            "pub fn NavigationMenu(",
            "pub fn Progress(",
            "pub fn Meter(",
            "pub fn DialogOverlay(",
            "pub fn DialogContent(",
        ),
        "shared Leptos component surface",
    )
    require(
        css,
        (
            ":focus-visible",
            "@media (prefers-reduced-motion: reduce)",
            "@media (forced-colors: active)",
            "@media (prefers-color-scheme: light)",
            "@media (max-width: 48rem)",
        ),
        "desktop CSS accessibility",
    )
    require(
        journey,
        (
            "keyboard_equivalent_fake_journey",
            "fake_crash_and_device_loss",
            "simulate_fake_restart",
            "ExportState::Completed",
            "UploadState::Completed",
        ),
        "fake journey",
    )
    require(
        hardware_workflow,
        (
            "workflow_dispatch:",
            "desktop-real-hardware.py",
            "frame-macos-hardware",
            "macos_display_webm_v1",
            "scripts/frame desktop-macos-bundle",
            "sign-macos-local-app.sh verify-trusted",
            "--app-bundle target/release/bundle/macos/Frame.app",
            "FRAME_EXPECTED_APPLE_TEAM_ID",
            "Windows stays on the portable/unavailable shell",
        ),
        "protected hardware workflow",
    )
    require(
        hardware_validator,
        (
            'MACOS_DISPLAY_CAPABILITY = "macos_display_webm_v1"',
            'MACOS_BUNDLE_IDENTIFIER = "xyz.engmanager.frame"',
            '"macos_display_capture_partial"',
            'evidence.get("full_product_gate") != "not_claimed"',
            '"screen_capture_preauthorized"',
            "verify_signed_bundle",
            'evidence.get("source_sha") != args.expected_source_sha',
            'evidence.get("run_id") != args.expected_run_id',
            'evidence.get("designated_requirement_sha256") != requirement_sha256',
            "PROTECTED_FULL_PRODUCT_CASES",
            "validator deliberately has no full-product mode",
        ),
        "partial macOS hardware validator",
    )
    require(
        desktop_shell_smoke,
        (
            '"unavailable",',
            '"deterministic_fake",',
            '"native_macos_display",',
            '"native_windows_display_window_region",',
            'parser.add_argument("--expected-adapter", choices=ADAPTERS, required=True)',
            "f\"recorder_adapter={args.expected_adapter}\"",
        ),
        "production desktop shell smoke",
    )
    require(
        architecture,
        (
            "Backend truth",
            "Composition and adapter truth",
            "Window ownership",
            "NativeMacOsDisplay",
            "display/window/region",
            "normalized `ScreenCaptureSource`/ingress/pump path",
            "optional exact 48 kHz stereo system-audio path",
            "excludes Frame's own process audio",
            "not a Studio project",
            "does not wire a usable previous-channel selector",
            "Production-mode build and smoke",
            "Fake adapter",
        ),
        "architecture",
    )
    require(
        adr,
        (
            "portable `tauri-app` build deliberately selects `Unavailable`",
            "`NativeMacOsDisplay` is not the complete recorder",
            "includes exact 48 kHz stereo system audio",
            "--features tauri-app,custom-protocol,macos-native",
            "--expected-adapter unavailable",
            "--expected-adapter native_macos_display",
            "protected capture hardware, assistive-technology",
        ),
        "desktop ADR",
    )
    require(
        screen_evidence,
        (
            "does not reclassify any checkbox",
            "Native macOS target source evidence",
            "MacOsNormalizedScreenCaptureSource",
            "optional exact 48 kHz stereo system audio",
            "display/window/region screen-only source wired; physical run pending",
            "does not start capture",
            "--expected-adapter native_macos_display",
        ),
        "screen capture evidence",
    )
    require(
        studio_evidence,
        (
            "It does not classify the complete Studio product path as locally implemented.",
            "optional exact 48 kHz stereo system audio",
            "not an edit-aware Studio export",
            "does not request capture permission",
            "not to those multitrack helpers or the Studio coordinator",
            "--expected-adapter native_macos_display",
        ),
        "Studio evidence",
    )
    require(
        evidence_doc,
        (
            "Local deterministic evidence",
            "Native macOS target source evidence",
            "screen-only recording uses the normalized",
            "Optional macOS system audio is the only native audio source currently supported",
            "Protected evidence still required",
            "publication journey; the native WebM path",
            "--expected-adapter native_macos_display",
        ),
        "evidence report",
    )
    require(
        operations,
        (
            "Build modes and current boundary",
            "direct A/V worker can optionally mux exact 48 kHz stereo system audio",
            "Crash and recovery",
            "`macos-native` has no durable journal or recovery-store composition.",
            "workflow and validator are not evidence that a physical run occurred",
            "current `macos-native` target-capture slice cannot execute this rollback procedure",
            "--expected-adapter unavailable",
            "--expected-adapter native_macos_display",
            "Rollback",
            "Real-hardware gate",
        ),
        "operations runbook",
    )
    for document, label in (
        (adr, "desktop ADR"),
        (architecture, "desktop architecture"),
        (screen_evidence, "screen evidence"),
        (studio_evidence, "Studio evidence"),
        (evidence_doc, "desktop evidence"),
        (operations, "desktop operations"),
    ):
        reject(
            document,
            (
                "not_selected",
                "NotSelected",
                "The release binary selects only `DesktopAdapterKind::Unavailable`",
                "A release binary selects `Unavailable`",
                "capture, microphone, system audio, camera",
                "rejects microphone, system audio, camera",
                "rejects audio, camera, window",
                "does not supply microphone,\nsystem-audio, or camera tracks",
                "all audio/camera inputs disabled",
                "display-video source and WebM path. It continues to refuse unsupported audio,\ncamera",
                "video-only VP8/WebM",
                "not support window/region capture, microphone, system audio, camera",
                "stop seals a single-source artifact",
                "display-video source and WebM path",
                "Windows, audio, camera",
                "Native macOS display-only source evidence",
                "records one full display",
                "does not support window/region capture",
                "macOS adapter is not yet connected",
                "current source Stop contract still has no bounded-tail return channel",
            ),
            label,
        )

    reviewed = [
        "apps/desktop/src/ipc.rs",
        "apps/desktop/src/runtime.rs",
        "apps/desktop/src/main.rs",
        "apps/desktop/Cargo.toml",
        "apps/desktop/Info.plist",
        "apps/desktop/src/native_backend.rs",
        "apps/desktop/src/macos_native_backend.rs",
        "apps/desktop/src/macos_native_backend/normalized_worker.rs",
        "apps/desktop/src/windows_native_backend.rs",
        "apps/desktop/src/gstreamer_bootstrap.rs",
        "crates/macos-screen-capture/src/lib.rs",
        "crates/macos-screen-capture/src/platform.rs",
        "crates/macos-screen-capture/src/normalized.rs",
        "crates/windows-screen-capture/src/normalized.rs",
        "crates/media/src/screen_capture.rs",
        "crates/media/src/screen_recording/pump.rs",
        "crates/media/src/screen_recording.rs",
        ".github/workflows/desktop-real-hardware.yml",
        "scripts/ci/desktop-real-hardware.py",
        "scripts/ci/test-desktop-real-hardware.py",
        "scripts/ci/sign-macos-local-app.sh",
        "scripts/ci/check-desktop-bundle.py",
        "scripts/ci/desktop-shell-smoke.py",
        "apps/desktop/ui/src/main.rs",
        "apps/desktop/ui/src/browser/region_picker.rs",
        "crates/ui/src/button.rs",
        "crates/ui/src/display.rs",
        "crates/ui/src/form.rs",
        "crates/ui/src/layout.rs",
        "crates/ui/styles/tailwind.css",
        "crates/ui/styles/tailwind.generated.css",
        "apps/desktop/capabilities/main.json",
        "apps/desktop/permissions/desktop.toml",
        "apps/desktop/permissions/autogenerated/finalize_instant.toml",
        "apps/desktop/tests/fake_desktop_journey.rs",
        "docs/adr/0005-leptos-rendering-and-tauri-shell.md",
        "docs/architecture/desktop-product-v1.md",
        "docs/evidence/screen-capture-local.md",
        "docs/evidence/studio-mode-local.md",
        "docs/evidence/desktop-editor-a11y-local.md",
        "docs/operations/desktop-recovery-and-release.md",
        "docs/operations/macos-display-recording-local.md",
        "scripts/ci/check-desktop-product.py",
    ]
    result = {
        "schema_version": 1,
        "evidence_class": "deterministic_desktop_product_review",
        "checks": {
            "typed_ipc": True,
            "logical_window_scopes": True,
            "backend_truth_runtime": True,
            "portable_unavailable_shell_source": True,
            "macos_native_target_source_contract": True,
            "macos_normalized_screen_only_worker": True,
            "windows_normalized_screen_only_worker": True,
            "windows_native_target_source_contract": True,
            "macos_window_region_selection": True,
            "bounded_native_stop_tail": True,
            "explicit_tauri_capabilities": True,
            "fake_pipeline_journey_present": True,
            "partial_macos_hardware_validator_present": True,
            "semantic_accessibility_surface": True,
            "real_hardware_evidence": False,
            "native_target_physical_evidence": False,
            "studio_edit_aware_integration": False,
            "native_recovery_evidence": False,
            "assistive_technology_evidence": False,
            "signed_distribution_runtime_evidence": False,
        },
        "reviewed_files": [
            {"path": path, "sha256": digest(path)} for path in reviewed
        ],
    }
    if args.evidence:
        destination = args.evidence.resolve()
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(
            json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
    print("desktop product, security, and accessibility boundary passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
